[package]
name = "finance"
version = "0.1.0"
authors = ["Alex Kouprin <hello@kikimora.tech>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "=4.0.0-pre.9"
near-sdk = "=4.0.0-pre.9"
